#!/usr/bin/env python3
"""Deterministically build the round-3 one-file teacher artifact.

Never tunes anything at build time: it reads the frozen config, validates that
the exact parameter set runs, and embeds src/portfolio_game_round3/core.py
verbatim so the shipped file is the tested file.

The grading contract (class name, BaseOptimization inheritance, fit, weights_)
is unchanged from rounds 1 and 2, and deliberately so, since the grader is the
same harness. The only round-3 difference in the adapter is that the short
budget now derives from the round's own leverage setting.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

ADAPTER_KEYS = ("method", "half_life", "recent_mix", "anchor_penalty",
                "gross_leverage")


def render(config_path: Path) -> str:
    cfg = json.loads(config_path.read_text(encoding="utf-8"))
    sys.path.insert(0, str(ROOT / "src"))
    from portfolio_game_round3.core import allocate
    import numpy as np
    params = {k: cfg[k] for k in ADAPTER_KEYS}
    allocate(np.zeros((3, 2)), **params)  # validate the exact frozen parameters
    core = (ROOT / "src/portfolio_game_round3/core.py").read_text(encoding="utf-8")
    digest = hashlib.sha256(core.encode()).hexdigest()
    header = (
        "# TEACHER SUBMISSION (round 3): upload this file alone.\n"
        "# 第三轮给老师只提交此文件；研究脚本、配置和原始样例不要一起上传。\n"
        "# Generated by tools/build_submission_round3.py; do not edit generated sections.\n"
        f"# Numerical core SHA256: {digest}\n"
        f"# Selection status: {cfg.get('selection_status', 'unspecified')}\n\n"
    )
    adapter = f'''


# ---- skfolio adapter: the required class; no constructor override ----
from sklearn.utils.validation import validate_data
from skfolio.optimization import BaseOptimization


class CVXPYPortfolio(BaseOptimization):
    """Round 3: return-only allocation, fully invested, rounded short budget.

    Prohibited this round: equal weight, inverse volatility, and global minimum
    variance on the sample covariance matrix. None of the three is formed on any
    code path -- the inverse-risk fallback of round 1 was deleted rather than
    reweighted, and the objective is an anchored variance problem on a shrunk
    and denoised covariance, not w'Sw on the sample covariance S.

    Round 3 raises leverage to 1.5. That is a cap on gross exposure, and this
    book is always fully invested, so net exposure is 1 and gross exposure is
    1 + 2 * (aggregate short). A cap of L therefore grants an aggregate short
    budget of exactly (L - 1) / 2, which is what `gross_leverage` is passed as.
    At L = 1 the budget is zero and the code path is the long-only one, term for
    term; the realised short and gross exposures are recorded in diagnostics_.

    The class name is fixed by the submission rules and does not imply that
    CVXPY is used as the numerical solver; the solver here is a bounded
    projected-gradient method with a convex duality-gap certificate.
    """

    def fit(self, X, y=None):
        # First perform the instructor-required validation. Relax ONLY the
        # finite-value check if necessary; shape/type checks still apply.
        try:
            returns = validate_data(self, X)
        except ValueError:
            returns = validate_data(self, X, ensure_all_finite=False)
        result = allocate(
            returns,
            method={params['method']!r},
            half_life={float(params['half_life'])!r},
            recent_mix={float(params['recent_mix'])!r},
            anchor_penalty={float(params['anchor_penalty'])!r},
            gross_leverage={float(params['gross_leverage'])!r},
        )
        self.weights_ = result["weights"]
        self.diagnostics_ = result["diagnostics"]
        self.solver_status_ = self.diagnostics_["status"]
        return self
'''
    return header + core + adapter


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path,
                        default=ROOT / "configs/submission_round3.json")
    parser.add_argument("--output", type=Path,
                        default=ROOT / "submission/portfolio_round3.py")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render(args.config)
    compile(text, str(args.output), "exec")
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != text:
            raise SystemExit("Submission is stale: run tools/build_submission_round3.py")
        print("Round-3 standalone submission matches core and frozen config.")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8")
        print(args.output.relative_to(ROOT) if args.output.is_relative_to(ROOT) else args.output)


if __name__ == "__main__":
    main()
